pipeline:
  name: PTE
  identifier: PTE
  projectIdentifier: VN
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: VikramGITPTE
        build: <+input>
  stages:
    - stage:
        name: Build_and_Push_PTE
        identifier: Build
        description: PTE CI Pipeline - Compile, Cache, Build & Push
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths:
              - /root/.cache/go-build
              - /go/pkg/mod
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Run
                  name: Install_Go
                  identifier: Install_Go
                  spec:
                    shell: Sh
                    command: |
                      sudo apt update
                      sudo apt install -y golang
                      go version
              - step:
                  type: Run
                  name: Go_Mod_Download
                  identifier: Go_Mod_Download
                  spec:
                    shell: Sh
                    command: |
                      go mod download
              - step:
                  type: Run
                  name: Go_Build
                  identifier: Go_Build
                  spec:
                    shell: Sh
                    command: |
                      go build -o app main.go
                      ls -l
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Vikram_Docker
                    repo: vikramtek/harness-pte
                    tags:
                      - pte-main-<+codebase.shortCommitSha>
                    dockerfile: Dockerfile
                    caching: true
